### ISSUE TITLE
Installation Question

### ISSUE THREAD

**Issue by GuevaraDev** [fbarresi/TwinCAT.JsonExtension#1]
How do I install the Extension, do i have to import the .cs code or add it as a library?

**Comment by fbarresi** [comment]
Hi,
The easiest way to use this library is to install it over nuget.
Just type in your package manager console: `Install-Package TwinCAT.JsonExtension`
or for .NET CLI: `dotnet add package TwinCAT.JsonExtension`

You can find more information about the installation of this package here: https://www.nuget.org/packages/TwinCAT.JsonExtension/
